models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    data_tests:
      - minimum_row_counts:
          arguments:
            min_row_counts: 1000
          config:
            severity: warn
    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{doc ("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_tests


  - name: dim_hosts_cleansed
    description: Cleaned version of the host table
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: primary key
        data_type: integer
      - name: host_name
        description: The name of host
        data_type: string
      - name: is_superhost
        description: Whether host is a super host or not
        data_type: string
      - name: created_at
        description: Date and time created
        data_type: timestamp
      - name: updated_at
        description: Date and time updated
        data_type: timestamp

  - name: dim_listings_w_hosts_cleansed
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              config:
                severity: warn
              arguments:
                min_value: 4000
                max_value: 8000
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: number